[package]
name = "christmas-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.11.0"
wasm-bindgen = "0.2.95"
yew = { version = "0.21.0", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.72"
features = ["console", "EventTarget", "DomRect", "Element", "SvgsvgElement", "HtmlElement", "TouchEvent", "TouchList", "Touch"]
