[package]
name = "tree-drawing-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.11.0"
log = "0.4.22"
usvg = "0.44.0"
wasm-bindgen = "0.2.95"
yew = { version = "0.21.0", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.72"
features = ["console", "EventTarget", "Window", "Performance", "Navigator","DomRect", "Element", "SvgsvgElement", "HtmlElement", "TouchEvent", "TouchList", "Touch"]
