[package]
name = "tree-drawing-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
gloo = "0.11.0"
js-sys = "0.3.72"
log = "0.4.22"
urlencoding = "2.1.3"
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
yew = { version = "0.21.0", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.72"
features = ["console",
            "EventTarget",
            "Window",
            "Performance",
            "Navigator",
            "DomRect",
            "Element",
            "SvgsvgElement",
            "HtmlElement", 
            "TouchEvent",
            "TouchList",
            "Touch",
            "CanvasRenderingContext2d",
            "HtmlCanvasElement",
            "ImageBitmap",
            "HtmlImageElement",
            "HtmlAnchorElement",
            "ShareData"
            ]
